name: CI/CD Pipeline

on: push

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        echo "No tests defined."

  docker-build:
    name: Build and Push Docker Image to ECR and Docker Hub
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Authenticate Docker to Amazon ECR
      run: |
        LOGIN_PASSWORD=$(aws ecr get-login-password --region us-east-1)
        echo $LOGIN_PASSWORD | docker login --username AWS --password-stdin 131095908738.dkr.ecr.us-east-1.amazonaws.com

    - name: Authenticate Docker to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t canonical-inteview .

    - name: Tag Docker image for ECR
      run: |
        docker tag canonical-inteview:latest 131095908738.dkr.ecr.us-east-1.amazonaws.com/canonical-inteview:latest

    - name: Push Docker image to Amazon ECR
      run: |
        docker push 131095908738.dkr.ecr.us-east-1.amazonaws.com/canonical-inteview:latest

  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to EC2
      run: |
        echo "${{ secrets.EC2_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << EOF
          # Ensure Docker is running
          sudo systemctl start docker
          
          # Log in to AWS ECR
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 131095908738.dkr.ecr.us-east-1.amazonaws.com

          # Pull the latest Docker image
          sudo docker pull 131095908738.dkr.ecr.us-east-1.amazonaws.com/canonical-inteview:latest

          # Stop and remove the old container
          sudo docker stop canonical-container || true
          sudo docker rm canonical-container || true

          # Run the new container
          sudo docker run -d --name canonical-container -p 80:80 131095908738.dkr.ecr.us-east-1.amazonaws.com/canonical-inteview:latest
        EOF

