name: CI/CD Pipeline

on: push

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        echo "No tests defined."

  docker-build:
    name: Build and Push Docker Image to ECR and Docker Hub
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Authenticate Docker to Amazon ECR
      run: |
        $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 131095908738.dkr.ecr.us-east-1.amazonaws.com)

    - name: Authenticate Docker to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t canonical-inteview .

    - name: Tag Docker image for ECR
      run: |
        docker tag canonical-inteview:latest 131095908738.dkr.ecr.us-east-1.amazonaws.com/canonical-inteview:latest

    - name: Push Docker image to Amazon ECR
      run: |
        docker push 131095908738.dkr.ecr.us-east-1.amazonaws.com/canonical-inteview:latest

    - name: Tag Docker image for Docker Hub
      run: |
        docker tag canonical-inteview:latest ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

  deploy:
    name: Deploy to AWS ECS
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Update ECS Service
      run: |
        aws ecs update-service \
          --cluster arn:aws:ecs:us-east-1:131095908738:cluster/canonical-interview-cluster \
          --service arn:aws:ecs:us-east-1:131095908738:service/canonical-interview-cluster/deploy-service \
          --force-new-deployment
